// <auto-generated />
using System;
using IMA.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IMA.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512020525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IMA.Web.Models.Investment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("assetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("porfolioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("purchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("purchasePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("ticket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("porfolioId");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("IMA.Web.Models.Portfolio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("IMA.Web.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("date")
                        .HasColumnType("numeric");

                    b.Property<int>("intvesmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("investmentid")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("investmentid");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("IMA.Web.Models.Investment", b =>
                {
                    b.HasOne("IMA.Web.Models.Portfolio", "porfolio")
                        .WithMany("investments")
                        .HasForeignKey("porfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("porfolio");
                });

            modelBuilder.Entity("IMA.Web.Models.Transaction", b =>
                {
                    b.HasOne("IMA.Web.Models.Investment", "investment")
                        .WithMany()
                        .HasForeignKey("investmentid");

                    b.Navigation("investment");
                });

            modelBuilder.Entity("IMA.Web.Models.Portfolio", b =>
                {
                    b.Navigation("investments");
                });
#pragma warning restore 612, 618
        }
    }
}
